/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  Ext_Project                            */
/*      FILE         :  Ext_Project.c                          */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX62N                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                              
                                                                           
                                                                           
#include <stdint.h>
#include "CONTROLLER.h"
#include "SYSTEM_HAL.h"
#include "SERIAL_Protocol.h"
/***********************************************************************/
/*                                                                     */
/*  FILE        :Main.c or Main.cpp                                    */
/*  DATE        :Tue, Oct 31, 2006                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :                                                      */
/*                                                                     */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif
void main(void)
{
#if (USE_BENCHMARK == 1)
	PORT1.DDR.BIT.B3 = 1;
	PORT1.DDR.BIT.B5 = 1;
#endif
	CONTROLLER_Init();
	Enable_Interrupt();
	/* Main Loop */
	while(1){
#if (USE_BENCHMARK == 1)
		PORT1.DR.BIT.B3 ^= 1;
#endif
		CONTROLLER_MainLoop();
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
